name: Xcode - Build

on: 
  push:
  pull_request:
  workflow_dispatch:
    inputs: 
      release__nightly:
        description: Create a nightly release
        type: boolean
        required: false

jobs:
  build:
    name: Build using xcodebuild command
    runs-on: macos-15
    env:
      scheme: GetMoreRam
      archive_path: archive
    outputs:
      scheme: ${{ steps.scheme.outputs.scheme }}
      archive_path: ${{ env.archive_path }}
    steps:
      - uses: maxim-lobanov/setup-xcode@b1
